export const Routes = {
  Auth: '/auth',
  ClassroomTypes: '/classroom-types',
  LessonStatuses: '/lesson-statuses',
  Terms: '/terms',
  TimetableUnits: '/timetable-units',
  Classrooms: '/classrooms',
  Students: '/students',
  Roles: '/roles',
  Institutions: '/institutions',
  Files: '/files',
  Users: '/users',
  InstitutionMembers: '/institution-members',
  Subjects: '/subjects',
  Grades: '/grades',
  Groups: '/groups',
  Lessons: '/lessons',
  Courses: '/courses',
} as const;